# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/devkitpro/msys2/usr/bin/cmake.exe

# The command to remove a file.
RM = /opt/devkitpro/msys2/usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = .

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = .

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/devkitpro/msys2/usr/bin/cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/devkitpro/msys2/usr/bin/cpack.exe --config ./CPackSourceConfig.cmake /home/carel/dolphinu/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/devkitpro/msys2/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carel/dolphinu/CMakeFiles /home/carel/dolphinu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carel/dolphinu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bdisasm

# Build rule for target.
bdisasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bdisasm
.PHONY : bdisasm

# fast build rule for target.
bdisasm/fast:
	$(MAKE) $(MAKESILENT) -f Externals/Bochs_disasm/CMakeFiles/bdisasm.dir/build.make Externals/Bochs_disasm/CMakeFiles/bdisasm.dir/build
.PHONY : bdisasm/fast

#=============================================================================
# Target rules for targets named glslang

# Build rule for target.
glslang: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glslang
.PHONY : glslang

# fast build rule for target.
glslang/fast:
	$(MAKE) $(MAKESILENT) -f Externals/glslang/CMakeFiles/glslang.dir/build.make Externals/glslang/CMakeFiles/glslang.dir/build
.PHONY : glslang/fast

#=============================================================================
# Target rules for targets named pugixml

# Build rule for target.
pugixml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml
.PHONY : pugixml

# fast build rule for target.
pugixml/fast:
	$(MAKE) $(MAKESILENT) -f Externals/pugixml/CMakeFiles/pugixml.dir/build.make Externals/pugixml/CMakeFiles/pugixml.dir/build
.PHONY : pugixml/fast

#=============================================================================
# Target rules for targets named cpp-optparse

# Build rule for target.
cpp-optparse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp-optparse
.PHONY : cpp-optparse

# fast build rule for target.
cpp-optparse/fast:
	$(MAKE) $(MAKESILENT) -f Externals/cpp-optparse/CMakeFiles/cpp-optparse.dir/build.make Externals/cpp-optparse/CMakeFiles/cpp-optparse.dir/build
.PHONY : cpp-optparse/fast

#=============================================================================
# Target rules for targets named enet

# Build rule for target.
enet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet
.PHONY : enet

# fast build rule for target.
enet/fast:
	$(MAKE) $(MAKESILENT) -f Externals/enet/CMakeFiles/enet.dir/build.make Externals/enet/CMakeFiles/enet.dir/build
.PHONY : enet/fast

#=============================================================================
# Target rules for targets named xxhash

# Build rule for target.
xxhash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xxhash
.PHONY : xxhash

# fast build rule for target.
xxhash/fast:
	$(MAKE) $(MAKESILENT) -f Externals/xxhash/CMakeFiles/xxhash.dir/build.make Externals/xxhash/CMakeFiles/xxhash.dir/build
.PHONY : xxhash/fast

#=============================================================================
# Target rules for targets named lzo2

# Build rule for target.
lzo2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lzo2
.PHONY : lzo2

# fast build rule for target.
lzo2/fast:
	$(MAKE) $(MAKESILENT) -f Externals/LZO/CMakeFiles/lzo2.dir/build.make Externals/LZO/CMakeFiles/lzo2.dir/build
.PHONY : lzo2/fast

#=============================================================================
# Target rules for targets named SoundTouch

# Build rule for target.
SoundTouch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SoundTouch
.PHONY : SoundTouch

# fast build rule for target.
SoundTouch/fast:
	$(MAKE) $(MAKESILENT) -f Externals/soundtouch/CMakeFiles/SoundTouch.dir/build.make Externals/soundtouch/CMakeFiles/SoundTouch.dir/build
.PHONY : SoundTouch/fast

#=============================================================================
# Target rules for targets named cubeb

# Build rule for target.
cubeb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cubeb
.PHONY : cubeb

# fast build rule for target.
cubeb/fast:
	$(MAKE) $(MAKESILENT) -f Externals/cubeb/CMakeFiles/cubeb.dir/build.make Externals/cubeb/CMakeFiles/cubeb.dir/build
.PHONY : cubeb/fast

#=============================================================================
# Target rules for targets named speex

# Build rule for target.
speex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 speex
.PHONY : speex

# fast build rule for target.
speex/fast:
	$(MAKE) $(MAKESILENT) -f Externals/cubeb/CMakeFiles/speex.dir/build.make Externals/cubeb/CMakeFiles/speex.dir/build
.PHONY : speex/fast

#=============================================================================
# Target rules for targets named usb

# Build rule for target.
usb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 usb
.PHONY : usb

# fast build rule for target.
usb/fast:
	$(MAKE) $(MAKESILENT) -f Externals/libusb/CMakeFiles/usb.dir/build.make Externals/libusb/CMakeFiles/usb.dir/build
.PHONY : usb/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f Externals/SFML/CMakeFiles/sfml-network.dir/build.make Externals/SFML/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f Externals/SFML/CMakeFiles/sfml-system.dir/build.make Externals/SFML/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named miniupnpc

# Build rule for target.
miniupnpc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miniupnpc
.PHONY : miniupnpc

# fast build rule for target.
miniupnpc/fast:
	$(MAKE) $(MAKESILENT) -f Externals/miniupnpc/CMakeFiles/miniupnpc.dir/build.make Externals/miniupnpc/CMakeFiles/miniupnpc.dir/build
.PHONY : miniupnpc/fast

#=============================================================================
# Target rules for targets named SOIL

# Build rule for target.
SOIL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SOIL
.PHONY : SOIL

# fast build rule for target.
SOIL/fast:
	$(MAKE) $(MAKESILENT) -f Externals/SOIL/CMakeFiles/SOIL.dir/build.make Externals/SOIL/CMakeFiles/SOIL.dir/build
.PHONY : SOIL/fast

#=============================================================================
# Target rules for targets named hidapi

# Build rule for target.
hidapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hidapi
.PHONY : hidapi

# fast build rule for target.
hidapi/fast:
	$(MAKE) $(MAKESILENT) -f Externals/hidapi/CMakeFiles/hidapi.dir/build.make Externals/hidapi/CMakeFiles/hidapi.dir/build
.PHONY : hidapi/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f Externals/gtest/CMakeFiles/gtest.dir/build.make Externals/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f Externals/gtest/CMakeFiles/gtest_main.dir/build.make Externals/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named audiocommon

# Build rule for target.
audiocommon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 audiocommon
.PHONY : audiocommon

# fast build rule for target.
audiocommon/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/AudioCommon/CMakeFiles/audiocommon.dir/build.make Source/Core/AudioCommon/CMakeFiles/audiocommon.dir/build
.PHONY : audiocommon/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/Common/CMakeFiles/common.dir/build.make Source/Core/Common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/Core/CMakeFiles/core.dir/build.make Source/Core/Core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named discio

# Build rule for target.
discio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 discio
.PHONY : discio

# fast build rule for target.
discio/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/DiscIO/CMakeFiles/discio.dir/build.make Source/Core/DiscIO/CMakeFiles/discio.dir/build
.PHONY : discio/fast

#=============================================================================
# Target rules for targets named dolphin-nogui

# Build rule for target.
dolphin-nogui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dolphin-nogui
.PHONY : dolphin-nogui

# fast build rule for target.
dolphin-nogui/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui.dir/build.make Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui.dir/build
.PHONY : dolphin-nogui/fast

#=============================================================================
# Target rules for targets named inputcommon

# Build rule for target.
inputcommon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 inputcommon
.PHONY : inputcommon

# fast build rule for target.
inputcommon/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/InputCommon/CMakeFiles/inputcommon.dir/build.make Source/Core/InputCommon/CMakeFiles/inputcommon.dir/build
.PHONY : inputcommon/fast

#=============================================================================
# Target rules for targets named uicommon

# Build rule for target.
uicommon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uicommon
.PHONY : uicommon

# fast build rule for target.
uicommon/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/UICommon/CMakeFiles/uicommon.dir/build.make Source/Core/UICommon/CMakeFiles/uicommon.dir/build
.PHONY : uicommon/fast

#=============================================================================
# Target rules for targets named videocommon

# Build rule for target.
videocommon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 videocommon
.PHONY : videocommon

# fast build rule for target.
videocommon/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build
.PHONY : videocommon/fast

#=============================================================================
# Target rules for targets named videoogl

# Build rule for target.
videoogl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 videoogl
.PHONY : videoogl

# fast build rule for target.
videoogl/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/build.make Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/build
.PHONY : videoogl/fast

#=============================================================================
# Target rules for targets named videonull

# Build rule for target.
videonull: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 videonull
.PHONY : videonull

# fast build rule for target.
videonull/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/VideoBackends/Null/CMakeFiles/videonull.dir/build.make Source/Core/VideoBackends/Null/CMakeFiles/videonull.dir/build
.PHONY : videonull/fast

#=============================================================================
# Target rules for targets named videosoftware

# Build rule for target.
videosoftware: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 videosoftware
.PHONY : videosoftware

# fast build rule for target.
videosoftware/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/VideoBackends/Software/CMakeFiles/videosoftware.dir/build.make Source/Core/VideoBackends/Software/CMakeFiles/videosoftware.dir/build
.PHONY : videosoftware/fast

#=============================================================================
# Target rules for targets named videovulkan

# Build rule for target.
videovulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 videovulkan
.PHONY : videovulkan

# fast build rule for target.
videovulkan/fast:
	$(MAKE) $(MAKESILENT) -f Source/Core/VideoBackends/Vulkan/CMakeFiles/videovulkan.dir/build.make Source/Core/VideoBackends/Vulkan/CMakeFiles/videovulkan.dir/build
.PHONY : videovulkan/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/CMakeFiles/unittests.dir/build.make Source/UnitTests/CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

#=============================================================================
# Target rules for targets named unittests_stubhost

# Build rule for target.
unittests_stubhost: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unittests_stubhost
.PHONY : unittests_stubhost

# fast build rule for target.
unittests_stubhost/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/CMakeFiles/unittests_stubhost.dir/build.make Source/UnitTests/CMakeFiles/unittests_stubhost.dir/build
.PHONY : unittests_stubhost/fast

#=============================================================================
# Target rules for targets named BitFieldTest

# Build rule for target.
BitFieldTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BitFieldTest
.PHONY : BitFieldTest

# fast build rule for target.
BitFieldTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/BitFieldTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BitFieldTest.dir/build
.PHONY : BitFieldTest/fast

#=============================================================================
# Target rules for targets named BitSetTest

# Build rule for target.
BitSetTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BitSetTest
.PHONY : BitSetTest

# fast build rule for target.
BitSetTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/BitSetTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BitSetTest.dir/build
.PHONY : BitSetTest/fast

#=============================================================================
# Target rules for targets named BitUtilsTest

# Build rule for target.
BitUtilsTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BitUtilsTest
.PHONY : BitUtilsTest

# fast build rule for target.
BitUtilsTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/BitUtilsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BitUtilsTest.dir/build
.PHONY : BitUtilsTest/fast

#=============================================================================
# Target rules for targets named BlockingLoopTest

# Build rule for target.
BlockingLoopTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlockingLoopTest
.PHONY : BlockingLoopTest

# fast build rule for target.
BlockingLoopTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/BlockingLoopTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BlockingLoopTest.dir/build
.PHONY : BlockingLoopTest/fast

#=============================================================================
# Target rules for targets named BusyLoopTest

# Build rule for target.
BusyLoopTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BusyLoopTest
.PHONY : BusyLoopTest

# fast build rule for target.
BusyLoopTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/BusyLoopTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BusyLoopTest.dir/build
.PHONY : BusyLoopTest/fast

#=============================================================================
# Target rules for targets named CommonFuncsTest

# Build rule for target.
CommonFuncsTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CommonFuncsTest
.PHONY : CommonFuncsTest

# fast build rule for target.
CommonFuncsTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/CommonFuncsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/CommonFuncsTest.dir/build
.PHONY : CommonFuncsTest/fast

#=============================================================================
# Target rules for targets named EventTest

# Build rule for target.
EventTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EventTest
.PHONY : EventTest

# fast build rule for target.
EventTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/EventTest.dir/build.make Source/UnitTests/Common/CMakeFiles/EventTest.dir/build
.PHONY : EventTest/fast

#=============================================================================
# Target rules for targets named FifoQueueTest

# Build rule for target.
FifoQueueTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FifoQueueTest
.PHONY : FifoQueueTest

# fast build rule for target.
FifoQueueTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/FifoQueueTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FifoQueueTest.dir/build
.PHONY : FifoQueueTest/fast

#=============================================================================
# Target rules for targets named FixedSizeQueueTest

# Build rule for target.
FixedSizeQueueTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FixedSizeQueueTest
.PHONY : FixedSizeQueueTest

# fast build rule for target.
FixedSizeQueueTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/FixedSizeQueueTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FixedSizeQueueTest.dir/build
.PHONY : FixedSizeQueueTest/fast

#=============================================================================
# Target rules for targets named FlagTest

# Build rule for target.
FlagTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlagTest
.PHONY : FlagTest

# fast build rule for target.
FlagTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/FlagTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FlagTest.dir/build
.PHONY : FlagTest/fast

#=============================================================================
# Target rules for targets named MathUtilTest

# Build rule for target.
MathUtilTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MathUtilTest
.PHONY : MathUtilTest

# fast build rule for target.
MathUtilTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/MathUtilTest.dir/build.make Source/UnitTests/Common/CMakeFiles/MathUtilTest.dir/build
.PHONY : MathUtilTest/fast

#=============================================================================
# Target rules for targets named NandPathsTest

# Build rule for target.
NandPathsTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NandPathsTest
.PHONY : NandPathsTest

# fast build rule for target.
NandPathsTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/NandPathsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/NandPathsTest.dir/build
.PHONY : NandPathsTest/fast

#=============================================================================
# Target rules for targets named StringUtilTest

# Build rule for target.
StringUtilTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StringUtilTest
.PHONY : StringUtilTest

# fast build rule for target.
StringUtilTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/StringUtilTest.dir/build.make Source/UnitTests/Common/CMakeFiles/StringUtilTest.dir/build
.PHONY : StringUtilTest/fast

#=============================================================================
# Target rules for targets named SwapTest

# Build rule for target.
SwapTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SwapTest
.PHONY : SwapTest

# fast build rule for target.
SwapTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/SwapTest.dir/build.make Source/UnitTests/Common/CMakeFiles/SwapTest.dir/build
.PHONY : SwapTest/fast

#=============================================================================
# Target rules for targets named x64EmitterTest

# Build rule for target.
x64EmitterTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 x64EmitterTest
.PHONY : x64EmitterTest

# fast build rule for target.
x64EmitterTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Common/CMakeFiles/x64EmitterTest.dir/build.make Source/UnitTests/Common/CMakeFiles/x64EmitterTest.dir/build
.PHONY : x64EmitterTest/fast

#=============================================================================
# Target rules for targets named MMIOTest

# Build rule for target.
MMIOTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MMIOTest
.PHONY : MMIOTest

# fast build rule for target.
MMIOTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Core/CMakeFiles/MMIOTest.dir/build.make Source/UnitTests/Core/CMakeFiles/MMIOTest.dir/build
.PHONY : MMIOTest/fast

#=============================================================================
# Target rules for targets named PageFaultTest

# Build rule for target.
PageFaultTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PageFaultTest
.PHONY : PageFaultTest

# fast build rule for target.
PageFaultTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Core/CMakeFiles/PageFaultTest.dir/build.make Source/UnitTests/Core/CMakeFiles/PageFaultTest.dir/build
.PHONY : PageFaultTest/fast

#=============================================================================
# Target rules for targets named CoreTimingTest

# Build rule for target.
CoreTimingTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoreTimingTest
.PHONY : CoreTimingTest

# fast build rule for target.
CoreTimingTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Core/CMakeFiles/CoreTimingTest.dir/build.make Source/UnitTests/Core/CMakeFiles/CoreTimingTest.dir/build
.PHONY : CoreTimingTest/fast

#=============================================================================
# Target rules for targets named DSPAcceleratorTest

# Build rule for target.
DSPAcceleratorTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DSPAcceleratorTest
.PHONY : DSPAcceleratorTest

# fast build rule for target.
DSPAcceleratorTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Core/CMakeFiles/DSPAcceleratorTest.dir/build.make Source/UnitTests/Core/CMakeFiles/DSPAcceleratorTest.dir/build
.PHONY : DSPAcceleratorTest/fast

#=============================================================================
# Target rules for targets named DSPAssemblyTest

# Build rule for target.
DSPAssemblyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DSPAssemblyTest
.PHONY : DSPAssemblyTest

# fast build rule for target.
DSPAssemblyTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Core/CMakeFiles/DSPAssemblyTest.dir/build.make Source/UnitTests/Core/CMakeFiles/DSPAssemblyTest.dir/build
.PHONY : DSPAssemblyTest/fast

#=============================================================================
# Target rules for targets named ESFormatsTest

# Build rule for target.
ESFormatsTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ESFormatsTest
.PHONY : ESFormatsTest

# fast build rule for target.
ESFormatsTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/Core/CMakeFiles/ESFormatsTest.dir/build.make Source/UnitTests/Core/CMakeFiles/ESFormatsTest.dir/build
.PHONY : ESFormatsTest/fast

#=============================================================================
# Target rules for targets named VertexLoaderTest

# Build rule for target.
VertexLoaderTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VertexLoaderTest
.PHONY : VertexLoaderTest

# fast build rule for target.
VertexLoaderTest/fast:
	$(MAKE) $(MAKESILENT) -f Source/UnitTests/VideoCommon/CMakeFiles/VertexLoaderTest.dir/build.make Source/UnitTests/VideoCommon/CMakeFiles/VertexLoaderTest.dir/build
.PHONY : VertexLoaderTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... unittests"
	@echo "... BitFieldTest"
	@echo "... BitSetTest"
	@echo "... BitUtilsTest"
	@echo "... BlockingLoopTest"
	@echo "... BusyLoopTest"
	@echo "... CommonFuncsTest"
	@echo "... CoreTimingTest"
	@echo "... DSPAcceleratorTest"
	@echo "... DSPAssemblyTest"
	@echo "... ESFormatsTest"
	@echo "... EventTest"
	@echo "... FifoQueueTest"
	@echo "... FixedSizeQueueTest"
	@echo "... FlagTest"
	@echo "... MMIOTest"
	@echo "... MathUtilTest"
	@echo "... NandPathsTest"
	@echo "... PageFaultTest"
	@echo "... SOIL"
	@echo "... SoundTouch"
	@echo "... StringUtilTest"
	@echo "... SwapTest"
	@echo "... VertexLoaderTest"
	@echo "... audiocommon"
	@echo "... bdisasm"
	@echo "... common"
	@echo "... core"
	@echo "... cpp-optparse"
	@echo "... cubeb"
	@echo "... discio"
	@echo "... dolphin-nogui"
	@echo "... enet"
	@echo "... glslang"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... hidapi"
	@echo "... inputcommon"
	@echo "... lzo2"
	@echo "... miniupnpc"
	@echo "... pugixml"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... speex"
	@echo "... uicommon"
	@echo "... unittests_stubhost"
	@echo "... usb"
	@echo "... videocommon"
	@echo "... videonull"
	@echo "... videoogl"
	@echo "... videosoftware"
	@echo "... videovulkan"
	@echo "... x64EmitterTest"
	@echo "... xxhash"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

